# Generated by Django 5.2.5 on 2025-10-03 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('idTarefa', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.TextField()),
                ('setor', models.CharField(max_length=50)),
                ('prioridade', models.CharField(choices=[('baixa', 'baixa'), ('media', 'media'), ('alta', 'alta')], max_length=10)),
                ('data', models.DateField()),
                ('status', models.CharField(choices=[('feito', 'feito'), ('fazendo', 'fazendo'), ('aFazer', 'a fazer')], max_length=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appKanban.usuarios')),
            ],
        ),
    ]
