# Generated by Django 5.2.5 on 2025-08-27 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appKanban', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idTarefa', models.IntegerField()),
                ('descricao', models.TextField()),
                ('setor', models.CharField(max_length=50)),
                ('prioridade', models.CharField(choices=[('baixa', 'baixa'), ('media', 'media'), ('alta', 'alta')], max_length=10)),
                ('data', models.DateField()),
                ('status', models.CharField(choices=[('feito', 'feito'), ('fazendo', 'fazendo'), ('aFazer', 'a fazer')], max_length=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appKanban.usuarios')),
            ],
        ),
    ]
